### ISSUE TITLE
Can't download the database in Chrome

### ISSUE THREAD

**Issue by Shifterovich** [EFForg/privacybadger#1123]
Clicking the "Download" button (under "Export user data") doesn't do anything. The "Import" button probably works (file dialog shows).

**Comment by alexristich** [comment]
Hmm, is it showing any errors in the developer console in Chrome? This might be related to the use of base64 instead of UTF-8 for encoding, which should be fixed in the next push.

**Comment by Shifterovich** [comment]
Right, I thought I checked the console, but apparently did not.

```
Error in response to storage.get: InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Object.callback (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/src/options.js:169:57)
    at HTMLButtonElement.exportUserData (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/src/options.js:166:24)
    at HTMLButtonElement.dispatch (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/jquery-ui/js/jquery-2.2.4.min.js:3:7537)
    at HTMLButtonElement.r.handle (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/jquery-ui/js/jquery-2.2.4.min.js:3:5620)
```

Indeed an encoding issue.

**Comment by alexristich** [comment]
Awesome, thanks for the verification. This one was totally my fault by the way :) Not sure when the next push is planned but presumably very soon, so once that's up the export should work again!
