### ISSUE TITLE
Errors in background page console in Chrome

### ISSUE THREAD

**Issue by ghostwords** [EFForg/privacybadger#1248]
This one from `updateCount`
```
Error in response to tabs.get: TypeError: Cannot set property 'bgTab' of undefined
    at Object.callback (chrome-extension://gjockcbgfgncdjnhljbilabkaocdemei/src/background.js:515:39)
    at Badger.updateCount (chrome-extension://gjockcbgfgncdjnhljbilabkaocdemei/src/background.js:513:19)
    at chrome.webRequest.onBeforeRequest.addListener.urls (chrome-extension://gjockcbgfgncdjnhljbilabkaocdemei/src/background.js:714:14)
```
followed by these two, both from `updateBadge`
```
Unchecked runtime.lastError while running browserAction.setBadgeBackgroundColor: No tab with id: 1680.
    at Badger.updateBadge (chrome-extension://gjockcbgfgncdjnhljbilabkaocdemei/src/background.js:490:28)
    at Object.callback (chrome-extension://gjockcbgfgncdjnhljbilabkaocdemei/src/background.js:518:18)

Unchecked runtime.lastError while running browserAction.setBadgeText: No tab with id: 1680.
    at Badger.updateBadge (chrome-extension://gjockcbgfgncdjnhljbilabkaocdemei/src/background.js:492:26)
    at Object.callback (chrome-extension://gjockcbgfgncdjnhljbilabkaocdemei/src/background.js:518:18)
```

Sounds like at least the first error comes up in Firefox too: https://github.com/EFForg/privacybadger/issues/1201#issuecomment-279725541.

Sporadically reproducible by closing tabs (needs more investigation).

Previously: #410

**Comment by ghostwords** [comment]
Appears to be fixed by 854b5b9623f0127a3451aefa81355a290b896c13.
