### ISSUE TITLE
ipla.tv

### ISSUE THREAD

**Issue by FadeMind** [EFForg/privacybadger#2040]
Sample site: https://ipla.tv/wideo/rozrywka/Polsat-SuperHit-Festiwal/5004781/2017/5010711/Polsat-SuperHit-Festiwal-2017-Sopocki-Hit-Kabaretowy-Zycie-jest-piekne-cz-3/d065940e93d7238d9898aad36569fd1f

Chrome x64 @ Windows 
Privacy Badger lastest from Chrome Store

Hello, please **whitelist** these domains required by IPLA TV streaming service:
```
n-15-3.dcs.redcdn.pl
r.dcs.redcdn.pl
r-webcache-e6.dcs.redcdn.pl
b2c.redefine.pl
b2c-www.redefine.pl
getmedia.redefine.pl
media.redefine.pl
redevents-bigdata.redefine.pl
redirector.redefine.pl
s.redefine.pl
```
Regards

**Comment by ghostwords** [comment]
Hello! Could you run the following script in your Badger's background page console and share what it prints out?
```javascript
(function () {
  const STR = "redcdn";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
(function () {
  const STR = "redefine";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```
To get to the background page console in Chrome, visit `chrome://extensions`, make sure "Developer mode" is checked, click on the "background page" link in Privacy Badger's row, and select the Console tab.

In Firefox, visit `about:debugging`, enable add-on debugging, click Debug next to Privacy Badger, click the OK button on the popup warning about remote debugging, and enter the above script into the console after the >>.

**Comment by FadeMind** [comment]
Now After I added these domain to whitelist is working fine, even if I remove / re-add extension to chrome:
![20180531-002-screenshoot](https://user-images.githubusercontent.com/9846948/40791109-f54d743a-64f6-11e8-8ca4-6d1a7b9d65b5.png)
Console output
````
Error in response to tabs.query: TypeError: Cannot read property 'id' of undefined
    at chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/popup.js:561:18
    at Object.callback (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/popup.js:547:76)
    at getTab (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/popup.js:547:15)
    at HTMLDocument.<anonymous> (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/popup.js:558:3)
    at l (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/vendor/jquery-3.3.1.min.js:2:29375)
    at c (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/vendor/jquery-3.3.1.min.js:2:29677)
(function () {
  const STR = "redcdn";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
(function () {
  const STR = "redefine";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
VM133:3 **** ACTION_MAP for redcdn
VM133:4 Uncaught TypeError: Cannot read property 'getBadgerStorageObject' of undefined
    at <anonymous>:4:25
    at <anonymous>:11:2
(anonymous) @ VM133:4
(anonymous) @ VM133:11
```

**Comment by ghostwords** [comment]
Removing the extension wipes out your Privacy Badger's learning so it has to relearn to block stuff.

Also, it looks like you ran the code in the popup perhaps, not the background page, but if you reinstalled the extension, you no longer have the debug data I was looking for.

**Comment by FadeMind** [comment]
Maybe I should try in fresh profile so...:) (for testing)
