### ISSUE TITLE
tabs.query error in Chromium 66.0.3359.170

### ISSUE THREAD

**Issue by renatolond** [EFForg/privacybadger#2043]
Hi! I'm using Chromium Version 66.0.3359.170 (Official Build) Arch Linux (64-bit)

It seems frequently my privacy badger gets the following error:

```
Error in response to tabs.query: TypeError: Cannot read property 'id' of undefined
    at chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/popup.js:561:18
    at Object.callback (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/popup.js:547:76)
    at getTab (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/popup.js:547:15)
    at HTMLDocument.<anonymous> (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/popup.js:558:3)
    at l (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/vendor/jquery-3.3.1.min.js:2:29375)
    at c (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/lib/vendor/jquery-3.3.1.min.js:2:29677)
```

The result is that the extension popup keeps "jumping" and does not show the sites anymore.
If I open the popup before the page finishes loading it seems to work somehow.

**Comment by ghostwords** [comment]
I think the JavaScript error is unrelated to the issue. It happens when you right-click on Badger's toolbar icon and select "Inspect popup", right? Our popup doesn't support that way of inspection at this time; you can inspect it though by opening it normally and then right-clicking within it and selecting "Inspect".

**Comment by ghostwords** [comment]
I do think this is the same issue as #1917, which is caused by a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=838150).

**Comment by renatolond** [comment]
Makes sense, inspecting it normally yields no error. I did inspect with the right-click+ inspect popup :)

**Comment by ghostwords** [comment]
This should be fixed as of Chrome 70 (currently dev channel): https://bugs.chromium.org/p/chromium/issues/detail?id=838150#c11.

**Comment by renatolond** [comment]
I'm waiting for it to be available on arch and I'll test again :)
